### ISSUE TITLE
AH and item drop searches don't return results in Firefox Mobile

### ISSUE THREAD

**Issue by RAIST5150** [kaincenteno/xiweb#32]
Works fine in other browsers built on Chromium, including desktop Firefox... seems to be limited to Firefox mobile so far.

This MAY be related to the issue discovered back in the fall with the player online list where Kreidos caught this exception:

`Uncaught SyntaxError: import assertions are not currently supported playersonline.php:16:45`

This has since been resolved for that list.  May be something there that can be used as a model to fix these two functions?

**Comment by kaincenteno** [comment]
resolved by https://github.com/kaincenteno/xiweb/pull/33
